import { z } from 'zod';

export const CANONICAL_ROLE_CODES = [
  'AGENCY_ADMIN',
  'CLIENT_ADMIN',
  'MANAGER',
  'SALES_MANAGER',
  'TELECALLER',
  'SALESPERSON',
  'TEST_RIDE_EXECUTIVE',
  'INVENTORY_EXECUTIVE',
  'BILLING_DOCUMENTATION_EXECUTIVE',
  'DELIVERY_EXECUTIVE',
  'RC_REGISTRATION_EXECUTIVE',
  'TEAM_MANAGER',
] as const;

export const PERMISSION_CODES = [
  'account.profile.read',
  'account.profile.update',
  'account.sessions.read',
  'account.sessions.revoke',
  'account.tenant.select',
  'organization.clients.read',
  'organization.branches.read',
  'organization.teams.read',
  'organization.users.read',
  'organization.users.manage',
  'organization.roles.read',
  'organization.roles.manage',
  'organization.sessions.manage',
  'organization.branches.manage',
  'organization.teams.manage',
  'organization.settings.manage',
  'organization.audit.read',
  'leads.read',
  'leads.create',
  'leads.transition',
  'leads.assign',
  'leads.followups.manage',
  'leads.notes.create',
  'leads.tasks.manage',
  'leads.duplicates.manage',
  'leads.sla.manage',
  'platform.agencies.manage',
  'platform.clients.manage',
  'platform.defaults.manage',
  'platform.support_elevation.manage',
  'organization.departments.read',
  'organization.departments.manage',
  'organization.hierarchy.read',
  'organization.hierarchy.manage',
  'telephony.calls.read',
  'telephony.calls.start',
  'telephony.outcomes.manage',
  'telephony.outcomes.override',
  'telephony.recordings.read',
  'telephony.recordings.upload',
  'telephony.connections.manage',
  'telephony.reconciliation.manage',
  'telephony.health.read',
  'messaging.conversations.read',
  'messaging.messages.send',
  'messaging.notes.create',
  'messaging.assignments.manage',
  'messaging.templates.read',
  'messaging.templates.manage',
  'messaging.connections.manage',
  'messaging.failures.manage',
  'messaging.media.read',
  'messaging.media.upload',
  'test_rides.read',
  'test_rides.schedule',
  'test_rides.assign',
  'test_rides.execute',
  'test_rides.location.write',
  'test_rides.active_map.read',
  'test_rides.cancel',
  'inventory.catalogue.read',
  'inventory.catalogue.manage',
  'inventory.units.read',
  'inventory.units.sensitive.read',
  'inventory.units.manage',
  'inventory.reservations.manage',
  'inventory.allocations.manage',
  'inventory.allocations.reallocate',
  'inventory.transfers.manage',
  'inventory.corrections.manage',
  'commercial.bookings.read',
  'commercial.bookings.manage',
  'commercial.bookings.cancel',
  'commercial.quotations.manage',
  'commercial.discounts.approve',
  'commercial.payments.record',
  'commercial.payments.verify',
  'commercial.payments.correct',
  'commercial.finance.manage',
  'commercial.insurance.manage',
  'commercial.exchange.manage',
  'commercial.exchange.approve',
  'commercial.invoices.manage',
  'commercial.documents.read',
  'commercial.documents.upload',
  'commercial.documents.verify',
  'commercial.readiness.read',
  'commercial.settings.manage',
  'delivery.jobs.read',
  'delivery.jobs.manage',
  'delivery.jobs.assign',
  'delivery.jobs.execute',
  'delivery.jobs.cancel',
  'delivery.checklists.manage',
  'delivery.proofs.upload',
  'delivery.proofs.review',
  'delivery.location.write',
  'delivery.active_map.read',
  'delivery.reschedules.approve',
  'delivery.settings.manage',
  'registration.cases.read',
  'registration.cases.manage',
  'registration.cases.assign',
  'registration.cases.execute',
  'registration.cases.close',
  'registration.cases.reopen',
  'registration.documents.upload',
  'registration.documents.review',
  'registration.documents.share',
  'registration.aging.read',
  'registration.settings.manage',
  'customer_vehicles.read',
  'customer_vehicles.manage',
  'reminders.read',
  'reminders.rules.manage',
  'reminders.generate',
  'reminders.dispatch.manage',
  'reminders.preferences.manage',
  'customer_activities.create',
] as const;

export const canonicalRoleCodeSchema = z.enum(CANONICAL_ROLE_CODES);
export const permissionCodeSchema = z.enum(PERMISSION_CODES);
export const membershipContextTypeSchema = z.enum(['AGENCY', 'CLIENT']);
export const membershipStatusSchema = z.enum(['INVITED', 'ACTIVE', 'SUSPENDED', 'ENDED']);
export const membershipScopeModeSchema = z.enum(['ALL', 'SELECTED', 'NONE']);
export const assignmentScopeSchema = z.enum([
  'ALL',
  'TEAM',
  'OWNED',
  'ASSIGNED',
  'OWNED_OR_ASSIGNED',
  'NONE',
]);
export const roleApplicationSchema = z.enum(['WEB', 'MOBILE']);

export type AssignmentScope = z.infer<typeof assignmentScopeSchema>;
export type CanonicalRoleCode = z.infer<typeof canonicalRoleCodeSchema>;
export type MembershipContextType = z.infer<typeof membershipContextTypeSchema>;
export type MembershipScopeMode = z.infer<typeof membershipScopeModeSchema>;
export type MembershipStatus = z.infer<typeof membershipStatusSchema>;
export type PermissionCode = z.infer<typeof permissionCodeSchema>;
export type RoleApplication = z.infer<typeof roleApplicationSchema>;
