import { z } from 'zod';

export const AUTH_ERROR_CODES = [
  'INVALID_CREDENTIALS',
  'ACCOUNT_SUSPENDED',
  'ACCOUNT_DISABLED',
  'MEMBERSHIP_REQUIRED',
  'MEMBERSHIP_INACTIVE',
  'CLIENT_INACTIVE',
  'SESSION_EXPIRED',
  'SESSION_REVOKED',
  'REFRESH_TOKEN_INVALID',
  'REFRESH_TOKEN_REUSED',
  'PASSWORD_RESET_TOKEN_INVALID',
  'MFA_REQUIRED',
  'MFA_ENROLLMENT_REQUIRED',
  'MFA_CHALLENGE_INVALID',
  'MFA_CHALLENGE_EXPIRED',
  'MFA_CODE_INVALID',
  'MFA_RECOVERY_CODE_INVALID',
  'SUPPORT_ELEVATION_REQUIRED',
  'SUPPORT_ELEVATION_EXPIRED',
  'SCOPE_DENIED',
] as const;

export const authErrorCodeSchema = z.enum(AUTH_ERROR_CODES);

export type AuthErrorCode = z.infer<typeof authErrorCodeSchema>;
