import type { AuthStore } from '../src/auth/auth-store.js';
import type { AuthRuntimeConfig } from '../src/auth/auth-runtime-config.js';

export const TEST_AUTH_CONFIG: AuthRuntimeConfig = {
  accessTokenAudience: 'gdm-test-clients',
  accessTokenIssuer: 'gdm-test-api',
  accessTokenSecret: 'test-access-token-secret-with-at-least-thirty-two-characters',
  accessTokenTtlSeconds: 300,
  cookieName: 'gdm_refresh',
  cookieSameSite: 'lax',
  cookieSecure: false,
  loginLockoutSeconds: 900,
  loginMaxAttempts: 5,
  mfaActiveKeyId: 'test-v1',
  mfaChallengePepper: 'test-mfa-challenge-pepper-with-at-least-thirty-two-characters',
  mfaChallengeTtlSeconds: 300,
  mfaEncryptionKeys: { 'test-v1': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=' },
  mfaIssuer: 'GDM Test',
  mfaMaxAttempts: 5,
  mfaRecoveryCodePepper: 'test-mfa-recovery-pepper-with-at-least-thirty-two-characters',
  googleChallengeTtlSeconds: 300,
  googleClientIds: ['123456789-test.apps.googleusercontent.com'],
  passwordPepper: 'test-password-pepper-with-at-least-thirty-two-characters',
  passwordResetTokenTtlSeconds: 1_800,
  refreshTokenPepper: 'test-refresh-token-pepper-with-at-least-thirty-two-characters',
  refreshTokenTtlSeconds: 2_592_000,
  supportElevationTtlSeconds: 900,
};

export function authStoreStub(overrides: Partial<AuthStore> = {}): AuthStore {
  const defaults: AuthStore = {
    consumeExternalAuthChallenge: () => Promise.resolve(undefined),
    consumePasswordReset: () => Promise.resolve({ kind: 'invalid' }),
    createPasswordReset: () => Promise.resolve(),
    createExternalAuthChallenge: () => Promise.resolve(),
    createMfaLoginChallenge: () => Promise.resolve(),
    createSession: () => Promise.resolve(),
    createSupportElevation: () => Promise.resolve(undefined),
    ensureSupabaseSession: () => Promise.resolve(undefined),
    findPasswordIdentity: () => Promise.resolve(undefined),
    getActiveMfaAuthenticator: () => Promise.resolve(undefined),
    getAuthenticationIdentity: () => Promise.resolve(undefined),
    getBranch: () => Promise.resolve(undefined),
    getMembership: () => Promise.resolve(undefined),
    getMfaAuthenticator: () => Promise.resolve(undefined),
    getMfaLoginChallenge: () => Promise.resolve(undefined),
    getSessionClientType: () => Promise.resolve(undefined),
    getTeam: () => Promise.resolve(undefined),
    listAgencyClients: () => Promise.resolve([]),
    listAuthenticationMethods: () => Promise.resolve([]),
    listAvailableMemberships: () => Promise.resolve([]),
    listBranches: () => Promise.resolve([]),
    listSessions: () => Promise.resolve([]),
    listTeams: () => Promise.resolve([]),
    listTenantUsers: () => Promise.resolve([]),
    recordAuthenticationAudit: () => Promise.resolve(),
    recordLoginFailure: () => Promise.resolve(),
    recordLoginSuccess: () => Promise.resolve(),
    recordMfaChallengeFailure: () => Promise.resolve(),
    resolveGoogleLoginIdentity: () => Promise.resolve({ kind: 'not_invited' }),
    resolveSession: () => Promise.resolve({ kind: 'session_revoked' }),
    revokeAllSessions: () => Promise.resolve(0),
    revokeByRefreshToken: () => Promise.resolve(false),
    revokeSession: () => Promise.resolve(false),
    revokeSupportElevation: () => Promise.resolve(false),
    rotateRefreshToken: () => Promise.resolve({ kind: 'invalid' }),
    switchMembership: () => Promise.resolve(undefined),
    startMfaEnrollment: () => Promise.resolve(undefined),
    completeMfaEnrollment: () => Promise.resolve(false),
    completeMfaRecoveryVerification: () => Promise.resolve(false),
    completeMfaTotpVerification: () => Promise.resolve(false),
    touchSession: () => Promise.resolve(),
    linkGoogleIdentity: () => Promise.resolve({ kind: 'identity_conflict' }),
    unlinkGoogleIdentity: () => Promise.resolve({ kind: 'identity_not_linked' }),
    validatePasswordReset: () => Promise.resolve(false),
  };

  return { ...defaults, ...overrides };
}
